# Site settings
title:
email: shane.caldwell12@ncf.edu
description: The best web application for bioinformatics you've never used.
baseurl: "/shinyLimma/" # the subpath of your site, e.g. /blog/
url: "www.shanecaldwell.info" # the base hostname & protocol for your site

twitter_username: coffeeDevRepeat
github_username: SJCaldwell

# Build settings
markdown: kramdown
